[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tensor-systems-specs"
version = "0.1.0"
description = "Tensor performance and integrity diagnostics for PyTorch"
authors = [{ name = "Gil" }]

[tool.setuptools.packages.find]
where = ["."]